using System;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;

namespace SignalForge.Application.Notifications;

/// <summary>
/// Real webhook provider: POSTs the notification as JSON to the recipient URL. A 2xx response is
/// an accepted delivery; the delivery id is taken from the <c>X-Delivery-Id</c> response header when
/// present, otherwise generated by the provider. Any other outcome throws
/// <see cref="NotificationDeliveryException"/>.
/// </summary>
public class WebhookNotificationProvider : INotificationProvider
{
    private readonly HttpClient _httpClient;
    private readonly ILogger<WebhookNotificationProvider> _logger;

    public const string DeliveryIdHeaderName = "X-Delivery-Id";

    public WebhookNotificationProvider(HttpClient httpClient, ILogger<WebhookNotificationProvider> logger)
    {
        _httpClient = httpClient;
        _logger = logger;
    }

    public string ProviderType => "webhook";

    public async Task<NotificationDeliveryResult> SendAsync(
        NotificationMessage message,
        CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(message);
        if (string.IsNullOrWhiteSpace(message.Recipient) || !Uri.TryCreate(message.Recipient, UriKind.Absolute, out _))
            throw new NotificationDeliveryException($"Webhook recipient must be an absolute URL, got '{message.Recipient}'.");

        var payload = new
        {
            recipient = message.Recipient,
            subject = message.Subject,
            body = message.Body
        };

        using var request = new HttpRequestMessage(HttpMethod.Post, message.Recipient)
        {
            Content = new StringContent(JsonSerializer.Serialize(payload), Encoding.UTF8, "application/json")
        };

        try
        {
            using var response = await _httpClient.SendAsync(request, cancellationToken);

            if ((int)response.StatusCode < 200 || (int)response.StatusCode >= 300)
            {
                var body = await response.Content.ReadAsStringAsync(cancellationToken);
                throw new NotificationDeliveryException(
                    $"Webhook provider rejected the notification with status {(int)response.StatusCode}: {body}");
            }

            var deliveryId = response.Headers.TryGetValues(DeliveryIdHeaderName, out var values)
                ? values.FirstOrDefault()
                : null;
            if (string.IsNullOrWhiteSpace(deliveryId))
                deliveryId = $"webhook-{Guid.NewGuid():N}";

            _logger.LogInformation(
                "Webhook notification delivered to {Recipient} with deliveryId {deliveryId} (HTTP {StatusCode})",
                message.Recipient, deliveryId, (int)response.StatusCode);

            return new NotificationDeliveryResult(
                deliveryId,
                ProviderType,
                NotificationDeliveryStatus.Accepted,
                DateTime.UtcNow);
        }
        catch (OperationCanceledException) when (!cancellationToken.IsCancellationRequested)
        {
            throw new NotificationDeliveryException("Webhook provider request timed out.");
        }
        catch (NotificationDeliveryException)
        {
            throw;
        }
        catch (HttpRequestException ex)
        {
            throw new NotificationDeliveryException($"Webhook provider transport error: {ex.Message}", ex);
        }
    }
}